# Generated by Django 4.2.3 on 2023-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_source', models.CharField(max_length=200)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
