# Generated by Django 4.2.3 on 2023-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0002_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
